steps:
  # 1. Clone repository
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/suuenz/gcp-repo-01.git

  # 2. Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
      - '.'

  # 3. Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}

substitutions:
  _PROJECT_ID: eighth-vehicle-466618-g2
  _CINAME: dke-image
  _VERSION: v2.0

options:
  logging: CLOUD_LOGGING_ONLY
