steps:
  # 1. Clone repository
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/suuenz/gcp-repo-01.git

  # 2. Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
      - '.'

  # 3. Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}

  # 4. Update image in Kubernetes Deployment
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/ cicd-app-01
      - dke-image-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'

substitutions:
  _PROJECT_ID: eighth-vehicle-466618-g2
  _CINAME: myimgweb-sha256-1
  _VERSION: v3.0


options:
  logging: CLOUD_LOGGING_ONLY
